// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatikaApp.DataLayer.Concrete;

namespace PatikaApp.DataLayer.Migrations
{
    [DbContext(typeof(PatikaContext))]
    partial class PatikaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PatikaApp.EntityLayer.AdminInfo", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BootcampInfoId")
                        .HasColumnType("int");

                    b.Property<int>("EducatorInfoId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("BootcampInfoId");

                    b.HasIndex("EducatorInfoId");

                    b.ToTable("AdminInfos");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AdminEmail = "mahir@hotmail.com",
                            AdminName = "Mahir",
                            BootcampInfoId = 1,
                            EducatorInfoId = 1
                        },
                        new
                        {
                            AdminId = 2,
                            AdminEmail = "ince@hotmail.com",
                            AdminName = "Serkan",
                            BootcampInfoId = 2,
                            EducatorInfoId = 2
                        });
                });

            modelBuilder.Entity("PatikaApp.EntityLayer.BootcampInfo", b =>
                {
                    b.Property<int>("BootcampId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BootcampContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BootcampName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BootcampId");

                    b.ToTable("BootcampInfos");

                    b.HasData(
                        new
                        {
                            BootcampId = 1,
                            BootcampContent = ".Net Eğitimi",
                            BootcampName = "Arvato Bootcamp"
                        },
                        new
                        {
                            BootcampId = 2,
                            BootcampContent = "React Eğitimi",
                            BootcampName = "Kodluyoruz Bootcamp"
                        });
                });

            modelBuilder.Entity("PatikaApp.EntityLayer.EducatorInfo", b =>
                {
                    b.Property<int>("EducatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EducatorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducatorSurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducatorId");

                    b.ToTable("EducatorInfos");

                    b.HasData(
                        new
                        {
                            EducatorId = 1,
                            EducatorEmail = "inceSerkan@gmail.com",
                            EducatorName = "Serkan",
                            EducatorSurName = "Ince"
                        },
                        new
                        {
                            EducatorId = 2,
                            EducatorEmail = "guzel@gmail.com",
                            EducatorName = "Zeynep",
                            EducatorSurName = "Guzel"
                        });
                });

            modelBuilder.Entity("PatikaApp.EntityLayer.AdminInfo", b =>
                {
                    b.HasOne("PatikaApp.EntityLayer.BootcampInfo", "BootcampInfo")
                        .WithMany("AdminInfos")
                        .HasForeignKey("BootcampInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatikaApp.EntityLayer.EducatorInfo", "EducatorInfo")
                        .WithMany("AdminInfos")
                        .HasForeignKey("EducatorInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BootcampInfo");

                    b.Navigation("EducatorInfo");
                });

            modelBuilder.Entity("PatikaApp.EntityLayer.BootcampInfo", b =>
                {
                    b.Navigation("AdminInfos");
                });

            modelBuilder.Entity("PatikaApp.EntityLayer.EducatorInfo", b =>
                {
                    b.Navigation("AdminInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
